on: [push,pull_request]


jobs:
  nikola_build:
    runs-on: ubuntu-latest
    name: 'Deploy Nikola to GitHub Pages'
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Build and Deploy Nikola
      uses: WWU-AMM/nikola-action@v4.0.1
      with:
        dry_run: ${{ github.ref_name != 'main' }}
